// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: runner/proto/runner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStatus int32

const (
	ExecutionStatus_SUCCESS ExecutionStatus = 0
	ExecutionStatus_FAILURE ExecutionStatus = 1
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	ExecutionStatus_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_proto_runner_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_runner_proto_runner_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{0}
}

type ConfigList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigList) Reset() {
	*x = ConfigList{}
	mi := &file_runner_proto_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigList) ProtoMessage() {}

func (x *ConfigList) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigList.ProtoReflect.Descriptor instead.
func (*ConfigList) Descriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConfigItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*ConfigItem_ValueConfig
	//	*ConfigItem_ValueList
	//	*ConfigItem_ValueString
	//	*ConfigItem_ValueInt
	Value         isConfigItem_Value `protobuf_oneof:"Value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	mi := &file_runner_proto_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigItem) GetValue() isConfigItem_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigItem) GetValueConfig() *ConfigItemSet {
	if x != nil {
		if x, ok := x.Value.(*ConfigItem_ValueConfig); ok {
			return x.ValueConfig
		}
	}
	return nil
}

func (x *ConfigItem) GetValueList() *ConfigList {
	if x != nil {
		if x, ok := x.Value.(*ConfigItem_ValueList); ok {
			return x.ValueList
		}
	}
	return nil
}

func (x *ConfigItem) GetValueString() string {
	if x != nil {
		if x, ok := x.Value.(*ConfigItem_ValueString); ok {
			return x.ValueString
		}
	}
	return ""
}

func (x *ConfigItem) GetValueInt() int32 {
	if x != nil {
		if x, ok := x.Value.(*ConfigItem_ValueInt); ok {
			return x.ValueInt
		}
	}
	return 0
}

type isConfigItem_Value interface {
	isConfigItem_Value()
}

type ConfigItem_ValueConfig struct {
	ValueConfig *ConfigItemSet `protobuf:"bytes,2,opt,name=ValueConfig,proto3,oneof"`
}

type ConfigItem_ValueList struct {
	ValueList *ConfigList `protobuf:"bytes,3,opt,name=ValueList,proto3,oneof"`
}

type ConfigItem_ValueString struct {
	ValueString string `protobuf:"bytes,4,opt,name=ValueString,proto3,oneof"`
}

type ConfigItem_ValueInt struct {
	ValueInt int32 `protobuf:"varint,5,opt,name=ValueInt,proto3,oneof"`
}

func (*ConfigItem_ValueConfig) isConfigItem_Value() {}

func (*ConfigItem_ValueList) isConfigItem_Value() {}

func (*ConfigItem_ValueString) isConfigItem_Value() {}

func (*ConfigItem_ValueInt) isConfigItem_Value() {}

type ConfigItemSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConfigItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItemSet) Reset() {
	*x = ConfigItemSet{}
	mi := &file_runner_proto_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItemSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemSet) ProtoMessage() {}

func (x *ConfigItemSet) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemSet.ProtoReflect.Descriptor instead.
func (*ConfigItemSet) Descriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigItemSet) GetItems() []*ConfigItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigItemSet         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_runner_proto_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureRequest) GetConfig() *ConfigItemSet {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_runner_proto_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type EvalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyPaths   []string               `protobuf:"bytes,1,rep,name=policyPaths,proto3" json:"policyPaths,omitempty"`
	ApiServer     uint32                 `protobuf:"varint,2,opt,name=apiServer,proto3" json:"apiServer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalRequest) Reset() {
	*x = EvalRequest{}
	mi := &file_runner_proto_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalRequest) ProtoMessage() {}

func (x *EvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalRequest.ProtoReflect.Descriptor instead.
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{5}
}

func (x *EvalRequest) GetPolicyPaths() []string {
	if x != nil {
		return x.PolicyPaths
	}
	return nil
}

func (x *EvalRequest) GetApiServer() uint32 {
	if x != nil {
		return x.ApiServer
	}
	return 0
}

// *
// EvalResponse is the result of an assessment check
// Results are sent back by the plugins using the Result service defined
// separately.
type EvalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ExecutionStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=proto.ExecutionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalResponse) Reset() {
	*x = EvalResponse{}
	mi := &file_runner_proto_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalResponse) ProtoMessage() {}

func (x *EvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalResponse.ProtoReflect.Descriptor instead.
func (*EvalResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_runner_proto_rawDescGZIP(), []int{6}
}

func (x *EvalResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_SUCCESS
}

var File_runner_proto_runner_proto protoreflect.FileDescriptor

const file_runner_proto_runner_proto_rawDesc = "" +
	"\n" +
	"\x19runner/proto/runner.proto\x12\x05proto\"\"\n" +
	"\n" +
	"ConfigList\x12\x14\n" +
	"\x05Items\x18\x01 \x03(\tR\x05Items\"\xd6\x01\n" +
	"\n" +
	"ConfigItem\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x128\n" +
	"\vValueConfig\x18\x02 \x01(\v2\x14.proto.ConfigItemSetH\x00R\vValueConfig\x121\n" +
	"\tValueList\x18\x03 \x01(\v2\x11.proto.ConfigListH\x00R\tValueList\x12\"\n" +
	"\vValueString\x18\x04 \x01(\tH\x00R\vValueString\x12\x1c\n" +
	"\bValueInt\x18\x05 \x01(\x05H\x00R\bValueIntB\a\n" +
	"\x05Value\"8\n" +
	"\rConfigItemSet\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.proto.ConfigItemR\x05items\"@\n" +
	"\x10ConfigureRequest\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.proto.ConfigItemSetR\x06config\")\n" +
	"\x11ConfigureResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"M\n" +
	"\vEvalRequest\x12 \n" +
	"\vpolicyPaths\x18\x01 \x03(\tR\vpolicyPaths\x12\x1c\n" +
	"\tapiServer\x18\x02 \x01(\rR\tapiServer\">\n" +
	"\fEvalResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.proto.ExecutionStatusR\x06status*+\n" +
	"\x0fExecutionStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x012y\n" +
	"\x06Runner\x12>\n" +
	"\tConfigure\x12\x17.proto.ConfigureRequest\x1a\x18.proto.ConfigureResponse\x12/\n" +
	"\x04Eval\x12\x12.proto.EvalRequest\x1a\x13.proto.EvalResponseB\tZ\a./protob\x06proto3"

var (
	file_runner_proto_runner_proto_rawDescOnce sync.Once
	file_runner_proto_runner_proto_rawDescData []byte
)

func file_runner_proto_runner_proto_rawDescGZIP() []byte {
	file_runner_proto_runner_proto_rawDescOnce.Do(func() {
		file_runner_proto_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_proto_runner_proto_rawDesc), len(file_runner_proto_runner_proto_rawDesc)))
	})
	return file_runner_proto_runner_proto_rawDescData
}

var file_runner_proto_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_runner_proto_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_runner_proto_runner_proto_goTypes = []any{
	(ExecutionStatus)(0),      // 0: proto.ExecutionStatus
	(*ConfigList)(nil),        // 1: proto.ConfigList
	(*ConfigItem)(nil),        // 2: proto.ConfigItem
	(*ConfigItemSet)(nil),     // 3: proto.ConfigItemSet
	(*ConfigureRequest)(nil),  // 4: proto.ConfigureRequest
	(*ConfigureResponse)(nil), // 5: proto.ConfigureResponse
	(*EvalRequest)(nil),       // 6: proto.EvalRequest
	(*EvalResponse)(nil),      // 7: proto.EvalResponse
}
var file_runner_proto_runner_proto_depIdxs = []int32{
	3, // 0: proto.ConfigItem.ValueConfig:type_name -> proto.ConfigItemSet
	1, // 1: proto.ConfigItem.ValueList:type_name -> proto.ConfigList
	2, // 2: proto.ConfigItemSet.items:type_name -> proto.ConfigItem
	3, // 3: proto.ConfigureRequest.config:type_name -> proto.ConfigItemSet
	0, // 4: proto.EvalResponse.status:type_name -> proto.ExecutionStatus
	4, // 5: proto.Runner.Configure:input_type -> proto.ConfigureRequest
	6, // 6: proto.Runner.Eval:input_type -> proto.EvalRequest
	5, // 7: proto.Runner.Configure:output_type -> proto.ConfigureResponse
	7, // 8: proto.Runner.Eval:output_type -> proto.EvalResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_runner_proto_runner_proto_init() }
func file_runner_proto_runner_proto_init() {
	if File_runner_proto_runner_proto != nil {
		return
	}
	file_runner_proto_runner_proto_msgTypes[1].OneofWrappers = []any{
		(*ConfigItem_ValueConfig)(nil),
		(*ConfigItem_ValueList)(nil),
		(*ConfigItem_ValueString)(nil),
		(*ConfigItem_ValueInt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_proto_runner_proto_rawDesc), len(file_runner_proto_runner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_proto_runner_proto_goTypes,
		DependencyIndexes: file_runner_proto_runner_proto_depIdxs,
		EnumInfos:         file_runner_proto_runner_proto_enumTypes,
		MessageInfos:      file_runner_proto_runner_proto_msgTypes,
	}.Build()
	File_runner_proto_runner_proto = out.File
	file_runner_proto_runner_proto_goTypes = nil
	file_runner_proto_runner_proto_depIdxs = nil
}
