// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runner/proto/types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvidenceStatusState int32

const (
	EvidenceStatusState_EVIDENCE_STATUS_STATE_SATISFIED     EvidenceStatusState = 0
	EvidenceStatusState_EVIDENCE_STATUS_STATE_NOT_SATISFIED EvidenceStatusState = 1
)

// Enum value maps for EvidenceStatusState.
var (
	EvidenceStatusState_name = map[int32]string{
		0: "EVIDENCE_STATUS_STATE_SATISFIED",
		1: "EVIDENCE_STATUS_STATE_NOT_SATISFIED",
	}
	EvidenceStatusState_value = map[string]int32{
		"EVIDENCE_STATUS_STATE_SATISFIED":     0,
		"EVIDENCE_STATUS_STATE_NOT_SATISFIED": 1,
	}
)

func (x EvidenceStatusState) Enum() *EvidenceStatusState {
	p := new(EvidenceStatusState)
	*p = x
	return p
}

func (x EvidenceStatusState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvidenceStatusState) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_proto_types_proto_enumTypes[0].Descriptor()
}

func (EvidenceStatusState) Type() protoreflect.EnumType {
	return &file_runner_proto_types_proto_enumTypes[0]
}

func (x EvidenceStatusState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvidenceStatusState.Descriptor instead.
func (EvidenceStatusState) EnumDescriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{0}
}

type SubjectType int32

const (
	SubjectType_SUBJECT_TYPE_INVENTORY_ITEM SubjectType = 0
	SubjectType_SUBJECT_TYPE_COMPONENT      SubjectType = 1
	SubjectType_SUBJECT_TYPE_USER           SubjectType = 2
	SubjectType_SUBJECT_TYPE_LOCATION       SubjectType = 3
	SubjectType_SUBJECT_TYPE_PARTY          SubjectType = 4
	SubjectType_SUBJECT_TYPE_RESOURCE       SubjectType = 5
)

// Enum value maps for SubjectType.
var (
	SubjectType_name = map[int32]string{
		0: "SUBJECT_TYPE_INVENTORY_ITEM",
		1: "SUBJECT_TYPE_COMPONENT",
		2: "SUBJECT_TYPE_USER",
		3: "SUBJECT_TYPE_LOCATION",
		4: "SUBJECT_TYPE_PARTY",
		5: "SUBJECT_TYPE_RESOURCE",
	}
	SubjectType_value = map[string]int32{
		"SUBJECT_TYPE_INVENTORY_ITEM": 0,
		"SUBJECT_TYPE_COMPONENT":      1,
		"SUBJECT_TYPE_USER":           2,
		"SUBJECT_TYPE_LOCATION":       3,
		"SUBJECT_TYPE_PARTY":          4,
		"SUBJECT_TYPE_RESOURCE":       5,
	}
)

func (x SubjectType) Enum() *SubjectType {
	p := new(SubjectType)
	*p = x
	return p
}

func (x SubjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_proto_types_proto_enumTypes[1].Descriptor()
}

func (SubjectType) Type() protoreflect.EnumType {
	return &file_runner_proto_types_proto_enumTypes[1]
}

func (x SubjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubjectType.Descriptor instead.
func (SubjectType) EnumDescriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{1}
}

type Property struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Property Name
	// A textual label, within a namespace, that identifies a specific attribute,
	// characteristic, or quality of the property's containing object.
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// Property Value
	// Indicates the value of the attribute, characteristic, or quality.
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	// Property Universally Unique Identifier
	// A unique identifier for a property.
	Uuid *string `protobuf:"bytes,3,opt,name=Uuid,proto3,oneof" json:"Uuid,omitempty"`
	// Property Namespace
	// A namespace qualifying the property's name. This allows different
	// organizations to associate distinct semantics with the same name.
	Ns *string `protobuf:"bytes,4,opt,name=Ns,proto3,oneof" json:"Ns,omitempty"`
	// Property Class
	// A textual label that provides a sub-type or characterization of the
	// property's name.
	Class *string `protobuf:"bytes,5,opt,name=Class,proto3,oneof" json:"Class,omitempty"`
	// Property Group
	// An identifier for relating distinct sets of properties.
	Group *string `protobuf:"bytes,6,opt,name=Group,proto3,oneof" json:"Group,omitempty"`
	// Remarks
	// Additional explanatory notes for the property.
	Remarks       *string `protobuf:"bytes,7,opt,name=Remarks,proto3,oneof" json:"Remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_runner_proto_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Property) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Property) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *Property) GetNs() string {
	if x != nil && x.Ns != nil {
		return *x.Ns
	}
	return ""
}

func (x *Property) GetClass() string {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return ""
}

func (x *Property) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *Property) GetRemarks() string {
	if x != nil && x.Remarks != nil {
		return *x.Remarks
	}
	return ""
}

type Link struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hypertext Reference
	// A resolvable URL reference to a resource.
	Href string `protobuf:"bytes,1,opt,name=Href,proto3" json:"Href,omitempty"`
	// Link Relation Type
	// Describes the type of relationship provided by the link's hypertext
	// reference. This can be an indicator of the link's purpose.
	Rel *string `protobuf:"bytes,2,opt,name=Rel,proto3,oneof" json:"Rel,omitempty"`
	// Media Type
	// A label that indicates the nature of a resource, as a data serialization or
	// format.
	MediaType *string `protobuf:"bytes,3,opt,name=MediaType,proto3,oneof" json:"MediaType,omitempty"`
	// Resource Fragment
	// In case where the href points to a back-matter/resource, this value will
	// indicate the URI fragment to append to any rlink associated with the
	// resource. This value MUST be URI encoded.
	ResourceFragment *string `protobuf:"bytes,4,opt,name=ResourceFragment,proto3,oneof" json:"ResourceFragment,omitempty"`
	// Link Text
	// A textual label to associate with the link, which may be used for
	// presentation in a tool.
	Text          *string `protobuf:"bytes,5,opt,name=Text,proto3,oneof" json:"Text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_runner_proto_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *Link) GetRel() string {
	if x != nil && x.Rel != nil {
		return *x.Rel
	}
	return ""
}

func (x *Link) GetMediaType() string {
	if x != nil && x.MediaType != nil {
		return *x.MediaType
	}
	return ""
}

func (x *Link) GetResourceFragment() string {
	if x != nil && x.ResourceFragment != nil {
		return *x.ResourceFragment
	}
	return ""
}

func (x *Link) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

type OriginActor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Links         []*Link                `protobuf:"bytes,5,rep,name=Links,proto3" json:"Links,omitempty"`
	Props         []*Property            `protobuf:"bytes,6,rep,name=Props,proto3" json:"Props,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OriginActor) Reset() {
	*x = OriginActor{}
	mi := &file_runner_proto_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginActor) ProtoMessage() {}

func (x *OriginActor) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginActor.ProtoReflect.Descriptor instead.
func (*OriginActor) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{2}
}

func (x *OriginActor) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *OriginActor) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OriginActor) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *OriginActor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OriginActor) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *OriginActor) GetProps() []*Property {
	if x != nil {
		return x.Props
	}
	return nil
}

type Origin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actors        []*OriginActor         `protobuf:"bytes,1,rep,name=Actors,proto3" json:"Actors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Origin) Reset() {
	*x = Origin{}
	mi := &file_runner_proto_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Origin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Origin) ProtoMessage() {}

func (x *Origin) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Origin.ProtoReflect.Descriptor instead.
func (*Origin) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{3}
}

func (x *Origin) GetActors() []*OriginActor {
	if x != nil {
		return x.Actors
	}
	return nil
}

type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          *string                `protobuf:"bytes,1,opt,name=UUID,proto3,oneof" json:"UUID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Remarks       *string                `protobuf:"bytes,4,opt,name=Remarks,proto3,oneof" json:"Remarks,omitempty"`
	Links         []*Link                `protobuf:"bytes,5,rep,name=Links,proto3" json:"Links,omitempty"`
	Props         []*Property            `protobuf:"bytes,6,rep,name=Props,proto3" json:"Props,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_runner_proto_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{4}
}

func (x *Step) GetUUID() string {
	if x != nil && x.UUID != nil {
		return *x.UUID
	}
	return ""
}

func (x *Step) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Step) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Step) GetRemarks() string {
	if x != nil && x.Remarks != nil {
		return *x.Remarks
	}
	return ""
}

func (x *Step) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Step) GetProps() []*Property {
	if x != nil {
		return x.Props
	}
	return nil
}

type Activity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          *string                `protobuf:"bytes,1,opt,name=UUID,proto3,oneof" json:"UUID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Remarks       *string                `protobuf:"bytes,4,opt,name=Remarks,proto3,oneof" json:"Remarks,omitempty"`
	Steps         []*Step                `protobuf:"bytes,5,rep,name=Steps,proto3" json:"Steps,omitempty"`
	Links         []*Link                `protobuf:"bytes,6,rep,name=Links,proto3" json:"Links,omitempty"`
	Props         []*Property            `protobuf:"bytes,7,rep,name=Props,proto3" json:"Props,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_runner_proto_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{5}
}

func (x *Activity) GetUUID() string {
	if x != nil && x.UUID != nil {
		return *x.UUID
	}
	return ""
}

func (x *Activity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Activity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Activity) GetRemarks() string {
	if x != nil && x.Remarks != nil {
		return *x.Remarks
	}
	return ""
}

func (x *Activity) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Activity) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Activity) GetProps() []*Property {
	if x != nil {
		return x.Props
	}
	return nil
}

type EvidenceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=Reason,proto3" json:"Reason,omitempty"`
	Remarks       string                 `protobuf:"bytes,2,opt,name=Remarks,proto3" json:"Remarks,omitempty"`
	State         EvidenceStatusState    `protobuf:"varint,3,opt,name=State,proto3,enum=proto.EvidenceStatusState" json:"State,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceStatus) Reset() {
	*x = EvidenceStatus{}
	mi := &file_runner_proto_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceStatus) ProtoMessage() {}

func (x *EvidenceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceStatus.ProtoReflect.Descriptor instead.
func (*EvidenceStatus) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{6}
}

func (x *EvidenceStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EvidenceStatus) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *EvidenceStatus) GetState() EvidenceStatusState {
	if x != nil {
		return x.State
	}
	return EvidenceStatusState_EVIDENCE_STATUS_STATE_SATISFIED
}

type PortRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	End           int32                  `protobuf:"varint,1,opt,name=End,proto3" json:"End,omitempty"`
	Start         int32                  `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	Transport     string                 `protobuf:"bytes,3,opt,name=Transport,proto3" json:"Transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	mi := &file_runner_proto_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{7}
}

func (x *PortRange) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *PortRange) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *PortRange) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

type Protocol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	PortRanges    []*PortRange           `protobuf:"bytes,4,rep,name=PortRanges,proto3" json:"PortRanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Protocol) Reset() {
	*x = Protocol{}
	mi := &file_runner_proto_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protocol) ProtoMessage() {}

func (x *Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protocol.ProtoReflect.Descriptor instead.
func (*Protocol) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{8}
}

func (x *Protocol) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Protocol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Protocol) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Protocol) GetPortRanges() []*PortRange {
	if x != nil {
		return x.PortRanges
	}
	return nil
}

type Component struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Remarks       string                 `protobuf:"bytes,5,opt,name=Remarks,proto3" json:"Remarks,omitempty"`
	Purpose       string                 `protobuf:"bytes,6,opt,name=Purpose,proto3" json:"Purpose,omitempty"`
	Protocols     []*Protocol            `protobuf:"bytes,7,rep,name=Protocols,proto3" json:"Protocols,omitempty"`
	Links         []*Link                `protobuf:"bytes,8,rep,name=Links,proto3" json:"Links,omitempty"`
	Props         []*Property            `protobuf:"bytes,9,rep,name=Props,proto3" json:"Props,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_runner_proto_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{9}
}

func (x *Component) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Component) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Component) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Component) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Component) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *Component) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *Component) GetProtocols() []*Protocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Component) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Component) GetProps() []*Property {
	if x != nil {
		return x.Props
	}
	return nil
}

type InventoryItemImplementedComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItemImplementedComponent) Reset() {
	*x = InventoryItemImplementedComponent{}
	mi := &file_runner_proto_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItemImplementedComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItemImplementedComponent) ProtoMessage() {}

func (x *InventoryItemImplementedComponent) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItemImplementedComponent.ProtoReflect.Descriptor instead.
func (*InventoryItemImplementedComponent) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{10}
}

func (x *InventoryItemImplementedComponent) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type InventoryItem struct {
	state                 protoimpl.MessageState               `protogen:"open.v1"`
	Identifier            string                               `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	Type                  string                               `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Title                 string                               `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Description           string                               `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Remarks               string                               `protobuf:"bytes,5,opt,name=Remarks,proto3" json:"Remarks,omitempty"`
	Links                 []*Link                              `protobuf:"bytes,6,rep,name=Links,proto3" json:"Links,omitempty"`
	Props                 []*Property                          `protobuf:"bytes,7,rep,name=Props,proto3" json:"Props,omitempty"`
	ImplementedComponents []*InventoryItemImplementedComponent `protobuf:"bytes,8,rep,name=ImplementedComponents,proto3" json:"ImplementedComponents,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_runner_proto_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{11}
}

func (x *InventoryItem) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *InventoryItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InventoryItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InventoryItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InventoryItem) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *InventoryItem) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *InventoryItem) GetProps() []*Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *InventoryItem) GetImplementedComponents() []*InventoryItemImplementedComponent {
	if x != nil {
		return x.ImplementedComponents
	}
	return nil
}

type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	Type          SubjectType            `protobuf:"varint,2,opt,name=Type,proto3,enum=proto.SubjectType" json:"Type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Remarks       string                 `protobuf:"bytes,4,opt,name=Remarks,proto3" json:"Remarks,omitempty"`
	Links         []*Link                `protobuf:"bytes,5,rep,name=Links,proto3" json:"Links,omitempty"`
	Props         []*Property            `protobuf:"bytes,6,rep,name=Props,proto3" json:"Props,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_runner_proto_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{12}
}

func (x *Subject) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Subject) GetType() SubjectType {
	if x != nil {
		return x.Type
	}
	return SubjectType_SUBJECT_TYPE_INVENTORY_ITEM
}

func (x *Subject) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Subject) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *Subject) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Subject) GetProps() []*Property {
	if x != nil {
		return x.Props
	}
	return nil
}

type Evidence struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UUID        string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description *string                `protobuf:"bytes,3,opt,name=Description,proto3,oneof" json:"Description,omitempty"`
	Remarks     *string                `protobuf:"bytes,4,opt,name=Remarks,proto3,oneof" json:"Remarks,omitempty"`
	// Assigning labels to Evidence makes it searchable and easily usable in the UI
	Labels map[string]string `protobuf:"bytes,5,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// When did we start collecting the evidence, and when did the process end, and how long is it valid for ?
	Start   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=Start,proto3" json:"Start,omitempty"`
	End     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=End,proto3" json:"End,omitempty"`
	Expires *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=Expires,proto3,oneof" json:"Expires,omitempty"`
	Links   []*Link                `protobuf:"bytes,9,rep,name=Links,proto3" json:"Links,omitempty"`
	Props   []*Property            `protobuf:"bytes,10,rep,name=Props,proto3" json:"Props,omitempty"`
	// Who or What is generating this evidence
	Origins []*Origin `protobuf:"bytes,11,rep,name=Origins,proto3" json:"Origins,omitempty"`
	// What steps did we take to create this evidence
	Activities []*Activity `protobuf:"bytes,12,rep,name=Activities,proto3" json:"Activities,omitempty"`
	// Which inventory items were discovered in the evaluation process ?
	InventoryItems []*InventoryItem `protobuf:"bytes,13,rep,name=InventoryItems,proto3" json:"InventoryItems,omitempty"`
	// Which components of the subject are being observed. A tool, user, policy etc.
	Components []*Component `protobuf:"bytes,14,rep,name=Components,proto3" json:"Components,omitempty"`
	// Who or What are we providing evidence for. What's under test.
	Subjects []*Subject `protobuf:"bytes,15,rep,name=Subjects,proto3" json:"Subjects,omitempty"`
	// Did we satisfy what was being tested for, or did we fail ?
	Status        *EvidenceStatus `protobuf:"bytes,16,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_runner_proto_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{13}
}

func (x *Evidence) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Evidence) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Evidence) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Evidence) GetRemarks() string {
	if x != nil && x.Remarks != nil {
		return *x.Remarks
	}
	return ""
}

func (x *Evidence) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Evidence) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Evidence) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Evidence) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

func (x *Evidence) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Evidence) GetProps() []*Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Evidence) GetOrigins() []*Origin {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *Evidence) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *Evidence) GetInventoryItems() []*InventoryItem {
	if x != nil {
		return x.InventoryItems
	}
	return nil
}

func (x *Evidence) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Evidence) GetSubjects() []*Subject {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *Evidence) GetStatus() *EvidenceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ThreatRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        string                 `protobuf:"bytes,1,opt,name=System,proto3" json:"System,omitempty"`
	ExternalID    string                 `protobuf:"bytes,2,opt,name=ExternalID,proto3" json:"ExternalID,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatRef) Reset() {
	*x = ThreatRef{}
	mi := &file_runner_proto_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatRef) ProtoMessage() {}

func (x *ThreatRef) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatRef.ProtoReflect.Descriptor instead.
func (*ThreatRef) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{14}
}

func (x *ThreatRef) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *ThreatRef) GetExternalID() string {
	if x != nil {
		return x.ExternalID
	}
	return ""
}

func (x *ThreatRef) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ThreatRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RemediationTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,2,opt,name=OrderIndex,proto3" json:"OrderIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemediationTask) Reset() {
	*x = RemediationTask{}
	mi := &file_runner_proto_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemediationTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemediationTask) ProtoMessage() {}

func (x *RemediationTask) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemediationTask.ProtoReflect.Descriptor instead.
func (*RemediationTask) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{15}
}

func (x *RemediationTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RemediationTask) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

type Remediation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Tasks         []*RemediationTask     `protobuf:"bytes,3,rep,name=Tasks,proto3" json:"Tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Remediation) Reset() {
	*x = Remediation{}
	mi := &file_runner_proto_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remediation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remediation) ProtoMessage() {}

func (x *Remediation) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remediation.ProtoReflect.Descriptor instead.
func (*Remediation) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{16}
}

func (x *Remediation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Remediation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Remediation) GetTasks() []*RemediationTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type RiskTemplateLabelSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskTemplateLabelSchema) Reset() {
	*x = RiskTemplateLabelSchema{}
	mi := &file_runner_proto_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskTemplateLabelSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskTemplateLabelSchema) ProtoMessage() {}

func (x *RiskTemplateLabelSchema) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskTemplateLabelSchema.ProtoReflect.Descriptor instead.
func (*RiskTemplateLabelSchema) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{17}
}

func (x *RiskTemplateLabelSchema) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RiskTemplateLabelSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RiskTemplate struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	UUID            string                     `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	PolicyPackage   string                     `protobuf:"bytes,2,opt,name=PolicyPackage,proto3" json:"PolicyPackage,omitempty"`
	Name            string                     `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Title           string                     `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	Statement       string                     `protobuf:"bytes,5,opt,name=Statement,proto3" json:"Statement,omitempty"`
	LikelihoodHint  string                     `protobuf:"bytes,6,opt,name=LikelihoodHint,proto3" json:"LikelihoodHint,omitempty"`
	ImpactHint      string                     `protobuf:"bytes,7,opt,name=ImpactHint,proto3" json:"ImpactHint,omitempty"`
	ViolationIds    []string                   `protobuf:"bytes,8,rep,name=ViolationIds,proto3" json:"ViolationIds,omitempty"`
	ThreatRefs      []*ThreatRef               `protobuf:"bytes,9,rep,name=ThreatRefs,proto3" json:"ThreatRefs,omitempty"`
	Remediation     *Remediation               `protobuf:"bytes,10,opt,name=Remediation,proto3" json:"Remediation,omitempty"`
	DedupeLabelKeys []string                   `protobuf:"bytes,15,rep,name=DedupeLabelKeys,proto3" json:"DedupeLabelKeys,omitempty"`
	LabelSchema     []*RiskTemplateLabelSchema `protobuf:"bytes,16,rep,name=LabelSchema,proto3" json:"LabelSchema,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RiskTemplate) Reset() {
	*x = RiskTemplate{}
	mi := &file_runner_proto_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskTemplate) ProtoMessage() {}

func (x *RiskTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskTemplate.ProtoReflect.Descriptor instead.
func (*RiskTemplate) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{18}
}

func (x *RiskTemplate) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *RiskTemplate) GetPolicyPackage() string {
	if x != nil {
		return x.PolicyPackage
	}
	return ""
}

func (x *RiskTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiskTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RiskTemplate) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *RiskTemplate) GetLikelihoodHint() string {
	if x != nil {
		return x.LikelihoodHint
	}
	return ""
}

func (x *RiskTemplate) GetImpactHint() string {
	if x != nil {
		return x.ImpactHint
	}
	return ""
}

func (x *RiskTemplate) GetViolationIds() []string {
	if x != nil {
		return x.ViolationIds
	}
	return nil
}

func (x *RiskTemplate) GetThreatRefs() []*ThreatRef {
	if x != nil {
		return x.ThreatRefs
	}
	return nil
}

func (x *RiskTemplate) GetRemediation() *Remediation {
	if x != nil {
		return x.Remediation
	}
	return nil
}

func (x *RiskTemplate) GetDedupeLabelKeys() []string {
	if x != nil {
		return x.DedupeLabelKeys
	}
	return nil
}

func (x *RiskTemplate) GetLabelSchema() []*RiskTemplateLabelSchema {
	if x != nil {
		return x.LabelSchema
	}
	return nil
}

type SubjectProp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectProp) Reset() {
	*x = SubjectProp{}
	mi := &file_runner_proto_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectProp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectProp) ProtoMessage() {}

func (x *SubjectProp) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectProp.ProtoReflect.Descriptor instead.
func (*SubjectProp) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{19}
}

func (x *SubjectProp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubjectProp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SubjectLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Href          string                 `protobuf:"bytes,1,opt,name=Href,proto3" json:"Href,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectLink) Reset() {
	*x = SubjectLink{}
	mi := &file_runner_proto_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectLink) ProtoMessage() {}

func (x *SubjectLink) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectLink.ProtoReflect.Descriptor instead.
func (*SubjectLink) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{20}
}

func (x *SubjectLink) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

type SubjectLabelSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectLabelSelector) Reset() {
	*x = SubjectLabelSelector{}
	mi := &file_runner_proto_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectLabelSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectLabelSelector) ProtoMessage() {}

func (x *SubjectLabelSelector) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectLabelSelector.ProtoReflect.Descriptor instead.
func (*SubjectLabelSelector) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{21}
}

func (x *SubjectLabelSelector) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SubjectLabelSelector) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SubjectLabelSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectLabelSchema) Reset() {
	*x = SubjectLabelSchema{}
	mi := &file_runner_proto_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectLabelSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectLabelSchema) ProtoMessage() {}

func (x *SubjectLabelSchema) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectLabelSchema.ProtoReflect.Descriptor instead.
func (*SubjectLabelSchema) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{22}
}

func (x *SubjectLabelSchema) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SubjectLabelSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SubjectTemplate struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	Name                string                  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                SubjectType             `protobuf:"varint,2,opt,name=Type,proto3,enum=proto.SubjectType" json:"Type,omitempty"`
	TitleTemplate       string                  `protobuf:"bytes,3,opt,name=TitleTemplate,proto3" json:"TitleTemplate,omitempty"`
	DescriptionTemplate string                  `protobuf:"bytes,4,opt,name=DescriptionTemplate,proto3" json:"DescriptionTemplate,omitempty"`
	PurposeTemplate     string                  `protobuf:"bytes,5,opt,name=PurposeTemplate,proto3" json:"PurposeTemplate,omitempty"`
	RemarksTemplate     string                  `protobuf:"bytes,6,opt,name=RemarksTemplate,proto3" json:"RemarksTemplate,omitempty"`
	IdentityLabelKeys   []string                `protobuf:"bytes,7,rep,name=IdentityLabelKeys,proto3" json:"IdentityLabelKeys,omitempty"`
	Props               []*SubjectProp          `protobuf:"bytes,8,rep,name=Props,proto3" json:"Props,omitempty"`
	Links               []*SubjectLink          `protobuf:"bytes,9,rep,name=Links,proto3" json:"Links,omitempty"`
	SelectorLabels      []*SubjectLabelSelector `protobuf:"bytes,10,rep,name=SelectorLabels,proto3" json:"SelectorLabels,omitempty"`
	LabelSchema         []*SubjectLabelSchema   `protobuf:"bytes,11,rep,name=LabelSchema,proto3" json:"LabelSchema,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubjectTemplate) Reset() {
	*x = SubjectTemplate{}
	mi := &file_runner_proto_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectTemplate) ProtoMessage() {}

func (x *SubjectTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectTemplate.ProtoReflect.Descriptor instead.
func (*SubjectTemplate) Descriptor() ([]byte, []int) {
	return file_runner_proto_types_proto_rawDescGZIP(), []int{23}
}

func (x *SubjectTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubjectTemplate) GetType() SubjectType {
	if x != nil {
		return x.Type
	}
	return SubjectType_SUBJECT_TYPE_INVENTORY_ITEM
}

func (x *SubjectTemplate) GetTitleTemplate() string {
	if x != nil {
		return x.TitleTemplate
	}
	return ""
}

func (x *SubjectTemplate) GetDescriptionTemplate() string {
	if x != nil {
		return x.DescriptionTemplate
	}
	return ""
}

func (x *SubjectTemplate) GetPurposeTemplate() string {
	if x != nil {
		return x.PurposeTemplate
	}
	return ""
}

func (x *SubjectTemplate) GetRemarksTemplate() string {
	if x != nil {
		return x.RemarksTemplate
	}
	return ""
}

func (x *SubjectTemplate) GetIdentityLabelKeys() []string {
	if x != nil {
		return x.IdentityLabelKeys
	}
	return nil
}

func (x *SubjectTemplate) GetProps() []*SubjectProp {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *SubjectTemplate) GetLinks() []*SubjectLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *SubjectTemplate) GetSelectorLabels() []*SubjectLabelSelector {
	if x != nil {
		return x.SelectorLabels
	}
	return nil
}

func (x *SubjectTemplate) GetLabelSchema() []*SubjectLabelSchema {
	if x != nil {
		return x.LabelSchema
	}
	return nil
}

var File_runner_proto_types_proto protoreflect.FileDescriptor

const file_runner_proto_types_proto_rawDesc = "" +
	"\n" +
	"\x18runner/proto/types.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x01\n" +
	"\bProperty\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\x12\x17\n" +
	"\x04Uuid\x18\x03 \x01(\tH\x00R\x04Uuid\x88\x01\x01\x12\x13\n" +
	"\x02Ns\x18\x04 \x01(\tH\x01R\x02Ns\x88\x01\x01\x12\x19\n" +
	"\x05Class\x18\x05 \x01(\tH\x02R\x05Class\x88\x01\x01\x12\x19\n" +
	"\x05Group\x18\x06 \x01(\tH\x03R\x05Group\x88\x01\x01\x12\x1d\n" +
	"\aRemarks\x18\a \x01(\tH\x04R\aRemarks\x88\x01\x01B\a\n" +
	"\x05_UuidB\x05\n" +
	"\x03_NsB\b\n" +
	"\x06_ClassB\b\n" +
	"\x06_GroupB\n" +
	"\n" +
	"\b_Remarks\"\xd2\x01\n" +
	"\x04Link\x12\x12\n" +
	"\x04Href\x18\x01 \x01(\tR\x04Href\x12\x15\n" +
	"\x03Rel\x18\x02 \x01(\tH\x00R\x03Rel\x88\x01\x01\x12!\n" +
	"\tMediaType\x18\x03 \x01(\tH\x01R\tMediaType\x88\x01\x01\x12/\n" +
	"\x10ResourceFragment\x18\x04 \x01(\tH\x02R\x10ResourceFragment\x88\x01\x01\x12\x17\n" +
	"\x04Text\x18\x05 \x01(\tH\x03R\x04Text\x88\x01\x01B\x06\n" +
	"\x04_RelB\f\n" +
	"\n" +
	"_MediaTypeB\x13\n" +
	"\x11_ResourceFragmentB\a\n" +
	"\x05_Text\"\xad\x01\n" +
	"\vOriginActor\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x16\n" +
	"\x06RoleId\x18\x03 \x01(\tR\x06RoleId\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12!\n" +
	"\x05Links\x18\x05 \x03(\v2\v.proto.LinkR\x05Links\x12%\n" +
	"\x05Props\x18\x06 \x03(\v2\x0f.proto.PropertyR\x05Props\"4\n" +
	"\x06Origin\x12*\n" +
	"\x06Actors\x18\x01 \x03(\v2\x12.proto.OriginActorR\x06Actors\"\xd5\x01\n" +
	"\x04Step\x12\x17\n" +
	"\x04UUID\x18\x01 \x01(\tH\x00R\x04UUID\x88\x01\x01\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1d\n" +
	"\aRemarks\x18\x04 \x01(\tH\x01R\aRemarks\x88\x01\x01\x12!\n" +
	"\x05Links\x18\x05 \x03(\v2\v.proto.LinkR\x05Links\x12%\n" +
	"\x05Props\x18\x06 \x03(\v2\x0f.proto.PropertyR\x05PropsB\a\n" +
	"\x05_UUIDB\n" +
	"\n" +
	"\b_Remarks\"\xfc\x01\n" +
	"\bActivity\x12\x17\n" +
	"\x04UUID\x18\x01 \x01(\tH\x00R\x04UUID\x88\x01\x01\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1d\n" +
	"\aRemarks\x18\x04 \x01(\tH\x01R\aRemarks\x88\x01\x01\x12!\n" +
	"\x05Steps\x18\x05 \x03(\v2\v.proto.StepR\x05Steps\x12!\n" +
	"\x05Links\x18\x06 \x03(\v2\v.proto.LinkR\x05Links\x12%\n" +
	"\x05Props\x18\a \x03(\v2\x0f.proto.PropertyR\x05PropsB\a\n" +
	"\x05_UUIDB\n" +
	"\n" +
	"\b_Remarks\"t\n" +
	"\x0eEvidenceStatus\x12\x16\n" +
	"\x06Reason\x18\x01 \x01(\tR\x06Reason\x12\x18\n" +
	"\aRemarks\x18\x02 \x01(\tR\aRemarks\x120\n" +
	"\x05State\x18\x03 \x01(\x0e2\x1a.proto.EvidenceStatusStateR\x05State\"Q\n" +
	"\tPortRange\x12\x10\n" +
	"\x03End\x18\x01 \x01(\x05R\x03End\x12\x14\n" +
	"\x05Start\x18\x02 \x01(\x05R\x05Start\x12\x1c\n" +
	"\tTransport\x18\x03 \x01(\tR\tTransport\"z\n" +
	"\bProtocol\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x120\n" +
	"\n" +
	"PortRanges\x18\x04 \x03(\v2\x10.proto.PortRangeR\n" +
	"PortRanges\"\xa4\x02\n" +
	"\tComponent\x12\x1e\n" +
	"\n" +
	"Identifier\x18\x01 \x01(\tR\n" +
	"Identifier\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12\x18\n" +
	"\aRemarks\x18\x05 \x01(\tR\aRemarks\x12\x18\n" +
	"\aPurpose\x18\x06 \x01(\tR\aPurpose\x12-\n" +
	"\tProtocols\x18\a \x03(\v2\x0f.proto.ProtocolR\tProtocols\x12!\n" +
	"\x05Links\x18\b \x03(\v2\v.proto.LinkR\x05Links\x12%\n" +
	"\x05Props\x18\t \x03(\v2\x0f.proto.PropertyR\x05Props\"C\n" +
	"!InventoryItemImplementedComponent\x12\x1e\n" +
	"\n" +
	"Identifier\x18\x01 \x01(\tR\n" +
	"Identifier\"\xbf\x02\n" +
	"\rInventoryItem\x12\x1e\n" +
	"\n" +
	"Identifier\x18\x01 \x01(\tR\n" +
	"Identifier\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12\x18\n" +
	"\aRemarks\x18\x05 \x01(\tR\aRemarks\x12!\n" +
	"\x05Links\x18\x06 \x03(\v2\v.proto.LinkR\x05Links\x12%\n" +
	"\x05Props\x18\a \x03(\v2\x0f.proto.PropertyR\x05Props\x12^\n" +
	"\x15ImplementedComponents\x18\b \x03(\v2(.proto.InventoryItemImplementedComponentR\x15ImplementedComponents\"\xd7\x01\n" +
	"\aSubject\x12\x1e\n" +
	"\n" +
	"Identifier\x18\x01 \x01(\tR\n" +
	"Identifier\x12&\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x12.proto.SubjectTypeR\x04Type\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x18\n" +
	"\aRemarks\x18\x04 \x01(\tR\aRemarks\x12!\n" +
	"\x05Links\x18\x05 \x03(\v2\v.proto.LinkR\x05Links\x12%\n" +
	"\x05Props\x18\x06 \x03(\v2\x0f.proto.PropertyR\x05Props\"\x9c\x06\n" +
	"\bEvidence\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12%\n" +
	"\vDescription\x18\x03 \x01(\tH\x00R\vDescription\x88\x01\x01\x12\x1d\n" +
	"\aRemarks\x18\x04 \x01(\tH\x01R\aRemarks\x88\x01\x01\x123\n" +
	"\x06Labels\x18\x05 \x03(\v2\x1b.proto.Evidence.LabelsEntryR\x06Labels\x120\n" +
	"\x05Start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05Start\x12,\n" +
	"\x03End\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x03End\x129\n" +
	"\aExpires\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x02R\aExpires\x88\x01\x01\x12!\n" +
	"\x05Links\x18\t \x03(\v2\v.proto.LinkR\x05Links\x12%\n" +
	"\x05Props\x18\n" +
	" \x03(\v2\x0f.proto.PropertyR\x05Props\x12'\n" +
	"\aOrigins\x18\v \x03(\v2\r.proto.OriginR\aOrigins\x12/\n" +
	"\n" +
	"Activities\x18\f \x03(\v2\x0f.proto.ActivityR\n" +
	"Activities\x12<\n" +
	"\x0eInventoryItems\x18\r \x03(\v2\x14.proto.InventoryItemR\x0eInventoryItems\x120\n" +
	"\n" +
	"Components\x18\x0e \x03(\v2\x10.proto.ComponentR\n" +
	"Components\x12*\n" +
	"\bSubjects\x18\x0f \x03(\v2\x0e.proto.SubjectR\bSubjects\x12-\n" +
	"\x06Status\x18\x10 \x01(\v2\x15.proto.EvidenceStatusR\x06Status\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_DescriptionB\n" +
	"\n" +
	"\b_RemarksB\n" +
	"\n" +
	"\b_Expires\"k\n" +
	"\tThreatRef\x12\x16\n" +
	"\x06System\x18\x01 \x01(\tR\x06System\x12\x1e\n" +
	"\n" +
	"ExternalID\x18\x02 \x01(\tR\n" +
	"ExternalID\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12\x10\n" +
	"\x03Url\x18\x04 \x01(\tR\x03Url\"G\n" +
	"\x0fRemediationTask\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12\x1e\n" +
	"\n" +
	"OrderIndex\x18\x02 \x01(\x05R\n" +
	"OrderIndex\"s\n" +
	"\vRemediation\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12,\n" +
	"\x05Tasks\x18\x03 \x03(\v2\x16.proto.RemediationTaskR\x05Tasks\"M\n" +
	"\x17RiskTemplateLabelSchema\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\"\xb6\x04\n" +
	"\fRiskTemplate\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12$\n" +
	"\rPolicyPackage\x18\x02 \x01(\tR\rPolicyPackage\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Title\x18\x04 \x01(\tR\x05Title\x12\x1c\n" +
	"\tStatement\x18\x05 \x01(\tR\tStatement\x12&\n" +
	"\x0eLikelihoodHint\x18\x06 \x01(\tR\x0eLikelihoodHint\x12\x1e\n" +
	"\n" +
	"ImpactHint\x18\a \x01(\tR\n" +
	"ImpactHint\x12\"\n" +
	"\fViolationIds\x18\b \x03(\tR\fViolationIds\x120\n" +
	"\n" +
	"ThreatRefs\x18\t \x03(\v2\x10.proto.ThreatRefR\n" +
	"ThreatRefs\x124\n" +
	"\vRemediation\x18\n" +
	" \x01(\v2\x12.proto.RemediationR\vRemediation\x12(\n" +
	"\x0fDedupeLabelKeys\x18\x0f \x03(\tR\x0fDedupeLabelKeys\x12@\n" +
	"\vLabelSchema\x18\x10 \x03(\v2\x1e.proto.RiskTemplateLabelSchemaR\vLabelSchemaJ\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fR\rTitleTemplateR\x11StatementTemplateR\x16LikelihoodHintTemplateR\x12ImpactHintTemplate\"7\n" +
	"\vSubjectProp\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"!\n" +
	"\vSubjectLink\x12\x12\n" +
	"\x04Href\x18\x01 \x01(\tR\x04Href\">\n" +
	"\x14SubjectLabelSelector\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"H\n" +
	"\x12SubjectLabelSchema\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\"\xfd\x03\n" +
	"\x0fSubjectTemplate\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12&\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x12.proto.SubjectTypeR\x04Type\x12$\n" +
	"\rTitleTemplate\x18\x03 \x01(\tR\rTitleTemplate\x120\n" +
	"\x13DescriptionTemplate\x18\x04 \x01(\tR\x13DescriptionTemplate\x12(\n" +
	"\x0fPurposeTemplate\x18\x05 \x01(\tR\x0fPurposeTemplate\x12(\n" +
	"\x0fRemarksTemplate\x18\x06 \x01(\tR\x0fRemarksTemplate\x12,\n" +
	"\x11IdentityLabelKeys\x18\a \x03(\tR\x11IdentityLabelKeys\x12(\n" +
	"\x05Props\x18\b \x03(\v2\x12.proto.SubjectPropR\x05Props\x12(\n" +
	"\x05Links\x18\t \x03(\v2\x12.proto.SubjectLinkR\x05Links\x12C\n" +
	"\x0eSelectorLabels\x18\n" +
	" \x03(\v2\x1b.proto.SubjectLabelSelectorR\x0eSelectorLabels\x12;\n" +
	"\vLabelSchema\x18\v \x03(\v2\x19.proto.SubjectLabelSchemaR\vLabelSchema*c\n" +
	"\x13EvidenceStatusState\x12#\n" +
	"\x1fEVIDENCE_STATUS_STATE_SATISFIED\x10\x00\x12'\n" +
	"#EVIDENCE_STATUS_STATE_NOT_SATISFIED\x10\x01*\xaf\x01\n" +
	"\vSubjectType\x12\x1f\n" +
	"\x1bSUBJECT_TYPE_INVENTORY_ITEM\x10\x00\x12\x1a\n" +
	"\x16SUBJECT_TYPE_COMPONENT\x10\x01\x12\x15\n" +
	"\x11SUBJECT_TYPE_USER\x10\x02\x12\x19\n" +
	"\x15SUBJECT_TYPE_LOCATION\x10\x03\x12\x16\n" +
	"\x12SUBJECT_TYPE_PARTY\x10\x04\x12\x19\n" +
	"\x15SUBJECT_TYPE_RESOURCE\x10\x05B\tZ\a./protob\x06proto3"

var (
	file_runner_proto_types_proto_rawDescOnce sync.Once
	file_runner_proto_types_proto_rawDescData []byte
)

func file_runner_proto_types_proto_rawDescGZIP() []byte {
	file_runner_proto_types_proto_rawDescOnce.Do(func() {
		file_runner_proto_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_proto_types_proto_rawDesc), len(file_runner_proto_types_proto_rawDesc)))
	})
	return file_runner_proto_types_proto_rawDescData
}

var file_runner_proto_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runner_proto_types_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_runner_proto_types_proto_goTypes = []any{
	(EvidenceStatusState)(0),                  // 0: proto.EvidenceStatusState
	(SubjectType)(0),                          // 1: proto.SubjectType
	(*Property)(nil),                          // 2: proto.Property
	(*Link)(nil),                              // 3: proto.Link
	(*OriginActor)(nil),                       // 4: proto.OriginActor
	(*Origin)(nil),                            // 5: proto.Origin
	(*Step)(nil),                              // 6: proto.Step
	(*Activity)(nil),                          // 7: proto.Activity
	(*EvidenceStatus)(nil),                    // 8: proto.EvidenceStatus
	(*PortRange)(nil),                         // 9: proto.PortRange
	(*Protocol)(nil),                          // 10: proto.Protocol
	(*Component)(nil),                         // 11: proto.Component
	(*InventoryItemImplementedComponent)(nil), // 12: proto.InventoryItemImplementedComponent
	(*InventoryItem)(nil),                     // 13: proto.InventoryItem
	(*Subject)(nil),                           // 14: proto.Subject
	(*Evidence)(nil),                          // 15: proto.Evidence
	(*ThreatRef)(nil),                         // 16: proto.ThreatRef
	(*RemediationTask)(nil),                   // 17: proto.RemediationTask
	(*Remediation)(nil),                       // 18: proto.Remediation
	(*RiskTemplateLabelSchema)(nil),           // 19: proto.RiskTemplateLabelSchema
	(*RiskTemplate)(nil),                      // 20: proto.RiskTemplate
	(*SubjectProp)(nil),                       // 21: proto.SubjectProp
	(*SubjectLink)(nil),                       // 22: proto.SubjectLink
	(*SubjectLabelSelector)(nil),              // 23: proto.SubjectLabelSelector
	(*SubjectLabelSchema)(nil),                // 24: proto.SubjectLabelSchema
	(*SubjectTemplate)(nil),                   // 25: proto.SubjectTemplate
	nil,                                       // 26: proto.Evidence.LabelsEntry
	(*timestamppb.Timestamp)(nil),             // 27: google.protobuf.Timestamp
}
var file_runner_proto_types_proto_depIdxs = []int32{
	3,  // 0: proto.OriginActor.Links:type_name -> proto.Link
	2,  // 1: proto.OriginActor.Props:type_name -> proto.Property
	4,  // 2: proto.Origin.Actors:type_name -> proto.OriginActor
	3,  // 3: proto.Step.Links:type_name -> proto.Link
	2,  // 4: proto.Step.Props:type_name -> proto.Property
	6,  // 5: proto.Activity.Steps:type_name -> proto.Step
	3,  // 6: proto.Activity.Links:type_name -> proto.Link
	2,  // 7: proto.Activity.Props:type_name -> proto.Property
	0,  // 8: proto.EvidenceStatus.State:type_name -> proto.EvidenceStatusState
	9,  // 9: proto.Protocol.PortRanges:type_name -> proto.PortRange
	10, // 10: proto.Component.Protocols:type_name -> proto.Protocol
	3,  // 11: proto.Component.Links:type_name -> proto.Link
	2,  // 12: proto.Component.Props:type_name -> proto.Property
	3,  // 13: proto.InventoryItem.Links:type_name -> proto.Link
	2,  // 14: proto.InventoryItem.Props:type_name -> proto.Property
	12, // 15: proto.InventoryItem.ImplementedComponents:type_name -> proto.InventoryItemImplementedComponent
	1,  // 16: proto.Subject.Type:type_name -> proto.SubjectType
	3,  // 17: proto.Subject.Links:type_name -> proto.Link
	2,  // 18: proto.Subject.Props:type_name -> proto.Property
	26, // 19: proto.Evidence.Labels:type_name -> proto.Evidence.LabelsEntry
	27, // 20: proto.Evidence.Start:type_name -> google.protobuf.Timestamp
	27, // 21: proto.Evidence.End:type_name -> google.protobuf.Timestamp
	27, // 22: proto.Evidence.Expires:type_name -> google.protobuf.Timestamp
	3,  // 23: proto.Evidence.Links:type_name -> proto.Link
	2,  // 24: proto.Evidence.Props:type_name -> proto.Property
	5,  // 25: proto.Evidence.Origins:type_name -> proto.Origin
	7,  // 26: proto.Evidence.Activities:type_name -> proto.Activity
	13, // 27: proto.Evidence.InventoryItems:type_name -> proto.InventoryItem
	11, // 28: proto.Evidence.Components:type_name -> proto.Component
	14, // 29: proto.Evidence.Subjects:type_name -> proto.Subject
	8,  // 30: proto.Evidence.Status:type_name -> proto.EvidenceStatus
	17, // 31: proto.Remediation.Tasks:type_name -> proto.RemediationTask
	16, // 32: proto.RiskTemplate.ThreatRefs:type_name -> proto.ThreatRef
	18, // 33: proto.RiskTemplate.Remediation:type_name -> proto.Remediation
	19, // 34: proto.RiskTemplate.LabelSchema:type_name -> proto.RiskTemplateLabelSchema
	1,  // 35: proto.SubjectTemplate.Type:type_name -> proto.SubjectType
	21, // 36: proto.SubjectTemplate.Props:type_name -> proto.SubjectProp
	22, // 37: proto.SubjectTemplate.Links:type_name -> proto.SubjectLink
	23, // 38: proto.SubjectTemplate.SelectorLabels:type_name -> proto.SubjectLabelSelector
	24, // 39: proto.SubjectTemplate.LabelSchema:type_name -> proto.SubjectLabelSchema
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_runner_proto_types_proto_init() }
func file_runner_proto_types_proto_init() {
	if File_runner_proto_types_proto != nil {
		return
	}
	file_runner_proto_types_proto_msgTypes[0].OneofWrappers = []any{}
	file_runner_proto_types_proto_msgTypes[1].OneofWrappers = []any{}
	file_runner_proto_types_proto_msgTypes[4].OneofWrappers = []any{}
	file_runner_proto_types_proto_msgTypes[5].OneofWrappers = []any{}
	file_runner_proto_types_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_proto_types_proto_rawDesc), len(file_runner_proto_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runner_proto_types_proto_goTypes,
		DependencyIndexes: file_runner_proto_types_proto_depIdxs,
		EnumInfos:         file_runner_proto_types_proto_enumTypes,
		MessageInfos:      file_runner_proto_types_proto_msgTypes,
	}.Build()
	File_runner_proto_types_proto = out.File
	file_runner_proto_types_proto_goTypes = nil
	file_runner_proto_types_proto_depIdxs = nil
}
