FROM golang:1.26.1 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ARG VERSION=dev
RUN go build -ldflags "-X main.version=${VERSION}" -o concom main.go


# 0.9.49.0
FROM cloudcustodian/c7n@sha256:275e79ff9fc4650f2aa7029a371beeab1a4101dcb975f2b29038e391880de902

COPY --from=builder /app/concom /app/concom

WORKDIR /app
ENTRYPOINT ["/app/concom"]
CMD ["agent", "-c", "/app/config.yml"]
