FROM golang:1.25.8 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o concom main.go


FROM cloudcustodian/c7n:0.9.49.0

COPY --from=builder /app/concom /app/concom

ENTRYPOINT ["/app/concom"]
CMD ["agent", "-c", "/app/config.yml"]
