FROM golang:1.26.1 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ARG VERSION=dev
RUN go build -ldflags "-X main.version=${VERSION}" -o concom main.go

FROM debian:bookworm-slim AS final
 
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*
 
WORKDIR /app
COPY --from=builder /app/concom /app/concom
 
CMD ["/bin/sh"]
